version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - cd drugservice
      - java -version
      - mvn package
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'drugservice'
